// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID      int       `json:"id"`
	Reviews []*Review `json:"reviews"`
}

func (Product) IsEntity() {}

type Review struct {
	ID      int      `json:"id"`
	Body    string   `json:"body"`
	Author  *User    `json:"author"`
	Product *Product `json:"product"`
}

func (Review) IsEntity() {}

type User struct {
	ID      int       `json:"id"`
	Reviews []*Review `json:"reviews"`
}

func (User) IsEntity() {}
