// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

func (Product) IsEntity() {}

type ProductList struct {
	Total int        `json:"total"`
	Data  []*Product `json:"data"`
}
