// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package internal

import (
	"github.com/gnanasuriyan/go-graphql/review-micro-service/graph"
	"github.com/gnanasuriyan/go-graphql/review-micro-service/resolvers"
	"github.com/gnanasuriyan/go-graphql/review-micro-service/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func GetApp() (*App, func(), error) {
	reviewService := &services.ReviewService{}
	userResolver := &resolvers.UserResolver{}
	productResolver := &resolvers.ProductResolver{}
	reviewResolver := &resolvers.ReviewResolver{}
	resolver := &graph.Resolver{
		IReviewService:   reviewService,
		IUserResolver:    userResolver,
		IProductResolver: productResolver,
		IReviewResolver:  reviewResolver,
	}
	app := &App{
		Resolver: resolver,
	}
	return app, func() {
	}, nil
}

// wire.go:

var serviceSet = wire.NewSet(services.NewReviewService)

var resolverSet = wire.NewSet(resolvers.NewUserResolver, resolvers.NewProductResolver, resolvers.NewReviewResolver)

type App struct {
	Resolver *graph.Resolver
}
