// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

func (User) IsEntity() {}

type UserList struct {
	Total int     `json:"total"`
	Data  []*User `json:"data"`
}
