// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package internal

import (
	"github.com/gnanasuriyan/go-graphql/user-micro-service/graph"
	"github.com/gnanasuriyan/go-graphql/user-micro-service/services"
	"github.com/google/wire"
)

// Injectors from wire..go:

func GetApp() (*App, func(), error) {
	userServiceOptions := &services.UserServiceOptions{}
	userService, err := services.InitUserService(userServiceOptions)
	if err != nil {
		return nil, nil, err
	}
	resolver := &graph.Resolver{
		IUserService: userService,
	}
	app := &App{
		Resolver: resolver,
	}
	return app, func() {
	}, nil
}

// wire..go:

var serviceSet = wire.NewSet(services.NewUserService)

type App struct {
	Resolver *graph.Resolver
}
