// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package internal

import (
	"github.com/gnanasuriyan/go-graphql/product-micro-service/graph"
	"github.com/gnanasuriyan/go-graphql/product-micro-service/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func GetApp() (*App, func(), error) {
	productService := &services.ProductService{}
	resolver := &graph.Resolver{
		IProductService: productService,
	}
	app := &App{
		Resolver: resolver,
	}
	return app, func() {
	}, nil
}

// wire.go:

var serviceSet = wire.NewSet(services.NewProductService)

type App struct {
	Resolver *graph.Resolver
}
